[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "yBbp1FLz9e"
weight = 9_999

[[main]]
name = "Tags"
pre = "tag"
pageRef = "tags"
identifier = "81R2B6OJaz"
weight = 9_999

[[footer]]
none = "none"
